"""Require page and file hashes to be unique

Revision ID: 2580e244ba18
Revises: 5da82c27cbf7
Create Date: 2022-08-04 08:35:00.490084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2580e244ba18'
down_revision = '5da82c27cbf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file', ['sha256'])
    op.create_unique_constraint(None, 'page', ['sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page', type_='unique')
    op.drop_constraint(None, 'file', type_='unique')
    # ### end Alembic commands ###
