"""Add key field to file

Revision ID: 6c655b04cdf5
Revises: b3163d6cf65d
Create Date: 2022-08-11 06:40:31.216061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c655b04cdf5'
down_revision = 'b3163d6cf65d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'file', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='unique')
    op.drop_column('file', 'key')
    # ### end Alembic commands ###
