"""empty message

Revision ID: b3163d6cf65d
Revises: 2580e244ba18
Create Date: 2022-08-11 04:53:21.242558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3163d6cf65d'
down_revision = '2580e244ba18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'content_disposition_filename')
    op.add_column('file_observation', sa.Column('content_disposition_unsafe_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_observation', 'content_disposition_unsafe_filename')
    op.add_column('file', sa.Column('content_disposition_filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
