"""Page referrer can be null, but file referrer can't

Revision ID: c32038686f51
Revises: ce160d5ec8dc
Create Date: 2022-08-11 06:58:44.678399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32038686f51'
down_revision = 'ce160d5ec8dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_observation', 'referrer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('page_observation', 'referrer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page_observation', 'referrer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('file_observation', 'referrer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
