"""Add key field to file

Revision ID: ce160d5ec8dc
Revises: 6c655b04cdf5
Create Date: 2022-08-11 06:41:23.074088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce160d5ec8dc'
down_revision = '6c655b04cdf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
